In [1]:
import numpy as np

In [2]:
my_list =[1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.add(my_list,my_mat)

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
my_list

[1, 2, 3]

In [9]:
l = np.array(my_mat)

In [10]:
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
o = np.array(my_list)

In [12]:
o

array([1, 2, 3])

In [13]:
np.add(l,o)

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [14]:
np.arange(0,80)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.zeros((6,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
np.linspace(0,5,1000)

array([0.        , 0.00500501, 0.01001001, 0.01501502, 0.02002002,
       0.02502503, 0.03003003, 0.03503504, 0.04004004, 0.04504505,
       0.05005005, 0.05505506, 0.06006006, 0.06506507, 0.07007007,
       0.07507508, 0.08008008, 0.08508509, 0.09009009, 0.0950951 ,
       0.1001001 , 0.10510511, 0.11011011, 0.11511512, 0.12012012,
       0.12512513, 0.13013013, 0.13513514, 0.14014014, 0.14514515,
       0.15015015, 0.15515516, 0.16016016, 0.16516517, 0.17017017,
       0.17517518, 0.18018018, 0.18518519, 0.19019019, 0.1951952 ,
       0.2002002 , 0.20520521, 0.21021021, 0.21521522, 0.22022022,
       0.22522523, 0.23023023, 0.23523524, 0.24024024, 0.24524525,
       0.25025025, 0.25525526, 0.26026026, 0.26526527, 0.27027027,
       0.27527528, 0.28028028, 0.28528529, 0.29029029, 0.2952953 ,
       0.3003003 , 0.30530531, 0.31031031, 0.31531532, 0.32032032,
       0.32532533, 0.33033033, 0.33533534, 0.34034034, 0.34534535,
       0.35035035, 0.35535536, 0.36036036, 0.36536537, 0.37037

In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
g= np.array_split(o,6)

In [36]:
g[2]

array([3])

In [42]:
np.fill_diagonal(np.zeros((2,3)),6)

In [46]:
np.random.rand(3,4,5)

array([[[0.55551739, 0.65526449, 0.02616799, 0.01588413, 0.2965131 ],
        [0.31117142, 0.74592631, 0.61062706, 0.7611195 , 0.17320687],
        [0.44339113, 0.94673386, 0.43180005, 0.2791278 , 0.92927503],
        [0.90177268, 0.95807926, 0.0845972 , 0.06716305, 0.73086125]],

       [[0.37364817, 0.72682177, 0.9402078 , 0.54680948, 0.13082537],
        [0.95657272, 0.22368856, 0.673416  , 0.89951473, 0.4687851 ],
        [0.49664366, 0.76252023, 0.31145034, 0.08349514, 0.02706811],
        [0.80088075, 0.04674096, 0.719365  , 0.89420275, 0.97150096]],

       [[0.15377311, 0.54551936, 0.11302325, 0.78595679, 0.31156284],
        [0.42903924, 0.79164979, 0.48484625, 0.52529634, 0.77919603],
        [0.84021667, 0.0281657 , 0.50487028, 0.11018132, 0.00383432],
        [0.0109894 , 0.84392898, 0.34032107, 0.7703372 , 0.76550601]]])

In [48]:
np.max(l)

9

In [49]:
l.max()

9

In [50]:
l.argmax()

8

In [66]:
l.any(0)

array([ True,  True,  True])

In [67]:
l.dtype

dtype('int32')

In [68]:
l[2].dtype

dtype('int32')

In [69]:
l[l>5]

array([6, 7, 8, 9])

In [70]:
y = np.arange(50)

In [71]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [76]:
y= y.reshape(5,10)

In [84]:
y[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [82]:
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])